### ISSUE TITLE
No confirmation for overwrite when pasting a file with existing filename

### ISSUE THREAD

**Issue by 7185** [karip/harbour-file-browser#15]
There should be a warning when pasting a file in a folder containing another file with the same filename, or at least rename the copied file (add " (1)" at the end of the filename or something).

**Comment by karip** [comment]
Hi! I’ve added a confirmation dialog for overwriting files. Sorry that it has taken a long time.. but better late than never.. :)

The confirmation dialog has three new strings which are shown when a file is copied over an existing file. If you know any languages other than English, it would be great if you could translate them. The strings are:

“Replace?” (this is shown as the title for the dialog)
“These files and folders already exist:”
“Replace” (command to replace files and folders)

Either just give the translations to me by commenting here or use Qt Linguist to translate the .ts files and create a pull request.

If you want to see how the confirmation dialog looks like, you can download the 1.7.4.1-alpha version from the [Releases](https://github.com/karip/harbour-file-browser/releases/tag/v1.7.4.1-alpha). It works on Sailfish 2.2.0 and later.

**Comment by 7185** [comment]
Hi! Sadly my Jolla phone died so I no longer use Sailfish.

Since I'm French I can still help with the French translation :

“Remplacer ?” (this is shown as the title for the dialog)
“Ces fichiers et répertoires existent déjà :”
“Remplacer” (command to replace files and folders)

Thank you!

**Comment by karip** [comment]
Oh, sorry to hear that about your phone. If you ever again get a Sailfish phone, I'm happy to tell you that File Browser has now a confirmation dialog.

Thanks for your help!
