### ISSUE TITLE
Translations ?

### ISSUE THREAD

**Issue by lutinotmalin** [karip/harbour-file-browser#31]
Hi mate !

I use your File Browser everyday on my device powered by Sailfish OS and it's by far the best one available on the Jolla Store. Many thanks for that !

However, I would absolutely love to use it in my own language. Any plans about translations within pull requests on GitHub or projects on Transifex ? 

Don't hesitate to warn me if you're planning to do it, I'd be glad to contribute with my French translation and I'm sure many other languages would pop up.

Cheers !

**Comment by karip** [comment]
The app has already [French translation](https://github.com/karip/harbour-file-browser/commit/5362d250f8afe3c6e9c545590a4f63f915fec414). It hasn't been published in the Jolla Store yet.

**Comment by lutinotmalin** [comment]
Nice. I will waiting then. Thx !
