### ISSUE TITLE
Some parts barely readable with new SF3 ambiences

### ISSUE THREAD

**Issue by Pohli** [karip/harbour-file-browser#37]
When using light ambience it's hard to read messages that appear at the top of the app like error messages. Same with Places selection.

**Comment by karip** [comment]
Thanks for pointing it out! I'm still running Sailfish 2 on my phone, so I hadn't noticed the new light ambiences in Sailfish 3.

I have now updated the app so that the colors should be better for light ambiences. Could you test it and confirm that it looks good now?

You can take the latest source code from this repository and compile it yourself. Or you can install the RPM package attached to this comment. The RPM package has been zipped, because Github doesn't allow RPM files in these comments. The app runs only on Sailfish 3 phones, because light ambience properties are not available in Sailfish 1 or 2.

[harbour-file-browser-1.7.4-0.armv7hl.rpm.zip](https://github.com/karip/harbour-file-browser/files/2975348/harbour-file-browser-1.7.4-0.armv7hl.rpm.zip)

**Comment by Pohli** [comment]
Can I use Install option in File Browser 1.7.3 and it will be updated automatically? Or do I have to close File Browser before and install per CLI?

**Comment by karip** [comment]
The file is a zip package, so you have to unzip it before you can install it. For instance, you can use the phone Terminal's unzip command. Once you have unzipped the RPM file, you can install it using File Browser. You have to restart File Browser to see the new version. The version should be 1.7.4 in the File Browser Settings after the restart.

**Comment by Pohli** [comment]
I get an error message: Problem with installing

**Comment by karip** [comment]
Sorry, there seems to be something wrong with it. I wasn't able to test it myself, because it works only on Sailfish 3 and I still have Sailfish 2 on my phone.

I will to get it to run on Sailfish 2, so that I can test it myself.

**Comment by karip** [comment]
Sorry for the delay getting this working. I found the reason why it didn't work. The OS version check had a mistake. It's now fixed.

The good thing is that I had some time to make other changes as well. The app now shows a confirmation dialog before overwriting files.

You can find an updated version at the [release section](https://github.com/karip/harbour-file-browser/releases/tag/v1.7.4.1-alpha) (v1.7.4.1-alpha). For phones, you should download harbour-file-browser-1.7.4.1-0.armv7hl.rpm and install it (it's not a zip archive).

It would be great if you could try the new alpha version and see if it looks good on your phone with a light ambience. I’ve tested the app on my Sailfish 2 phone and it looks ok on it.

Also, there’s three new translation strings in the app for OverwriteDialog, which is shown when a copied file already exists. If you know languages other than English, it would be great if you could translate the strings for the languages that you know. The strings are:

“Replace?” (a string shown as the title for the dialog)
“These files and folders already exist.”
“Replace” (command to replace files and folders)

Either just reply to me with the translations or use Qt Linguist to translate the .ts file and create a pull request.

Thanks!

**Comment by Pohli** [comment]
Thanks, it looks fine now!
About the strings: I don't know about Qt Linguist, maybe I'll look into it another time. I can tell you the strings in German right here as there are only three:

"Ersetzen?"
"Diese Dateien oder Ordner existieren schon:"
"Ersetzen"

I would also replace the full stop by a colon in the second string in the original English version like I did in my translation.

**Comment by karip** [comment]
Thanks for the translations. I added them to the app. Good point about the colon. I modified the text accordingly.

I'll try to get more translations for the texts, so it may take a while before the new version is available on Jolla Store. Its version will be 1.8.0.

Thanks again for you help!
