### ISSUE TITLE
Open in specific directory

### ISSUE THREAD

**Issue by llelectronics** [karip/harbour-file-browser#9]
It would be nice if one could open the file browser in a specific directory by giving the directory location as command line parameter. 

This would be also helpful for other applications that want to use harbour-file-browser to open a specific directory. 

Example: harbour-file-browser ~/Downloads
Expected result: Open File-Browser in the users Downloads directory

**Comment by karip** [comment]
You can find a more advanced version of File Browser which accepts folders as command line parameters at https://github.com/ichthyosaurus/harbour-file-browser
